# Generated by Django 5.0.1 on 2026-02-20 08:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., DIWALI50 or RAHUL10', max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('Fixed', 'Fixed Amount'), ('Percentage', 'Percentage (%)')], default='Percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Amount in ₹ or %', max_digits=10)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField()),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Leave blank for unlimited', null=True)),
                ('total_uses', models.PositiveIntegerField(default=0)),
                ('is_affiliate', models.BooleanField(default=False, help_text='Check this if given to a YouTuber/Freelancer')),
                ('affiliate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_revenue_generated', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.coupon'),
        ),
    ]
