# Generated by Django 6.0.2 on 2026-03-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_homehero_image_alter_partnerlogo_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='badge_color',
            field=models.CharField(blank=True, help_text='Hex color e.g. #FFC107', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='badge_text_color',
            field=models.CharField(blank=True, help_text='Hex color e.g. #000000', max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
