# Generated by Django 6.0.2 on 2026-03-24 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_homehero_image_alter_partnerlogo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homehero',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='image',
            field=models.ImageField(upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
