# Generated by Django 6.0.2 on 2026-03-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_homehero_image_alter_partnerlogo_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(help_text='e.g., 1 Pack, 2 Bottles', max_length=50)),
                ('image', models.ImageField(upload_to='combos/')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('reviews_count', models.IntegerField(default=5)),
                ('badge', models.CharField(blank=True, max_length=50, null=True)),
                ('badge_color', models.CharField(blank=True, max_length=7, null=True)),
                ('badge_text_color', models.CharField(blank=True, max_length=7, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Combo',
                'verbose_name_plural': 'Combos',
                'ordering': ['-created_at'],
            },
        ),
    ]
