# Generated by Django 6.0.2 on 2026-04-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_combo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_line1', models.CharField(help_text="First line of the title, e.g. 'Sourced from Healthy,'", max_length=200)),
                ('title_line2', models.CharField(blank=True, default='', help_text="Second line of the title, e.g. 'Well-Cared Cattle'", max_length=200)),
                ('image', models.ImageField(upload_to='process/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='homehero',
            name='order',
        ),
    ]
