# Generated by Django 6.0.2 on 2026-04-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_processstep_remove_homehero_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='homehero',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
