# Generated by Django 6.0.2 on 2026-04-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_homehero_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='combo',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price (shown as current price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='combo',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='MRP / original price (shown as strikethrough)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='current_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Selling price (shown as current price)', max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='MRP / original price (shown as strikethrough)', max_digits=10),
        ),
    ]
