# Generated by Django 6.0.2 on 2026-04-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_combo_price_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='modal_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown in quick-view modal (leave blank to use main description)'),
        ),
        migrations.AddField(
            model_name='combo',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', null=True, upload_to='combos/modal/'),
        ),
        migrations.AddField(
            model_name='product',
            name='modal_description',
            field=models.TextField(blank=True, default='', help_text='Detailed description shown in quick-view modal (leave blank to use main description)'),
        ),
        migrations.AddField(
            model_name='product',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', null=True, upload_to='products/modal/'),
        ),
    ]
