# Generated by Django 6.0.2 on 2026-04-06 07:53

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_combo_image_alter_combo_modal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='modal_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modal_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', max_length=255, null=True, verbose_name='image'),
        ),
    ]
