# Generated by Django 6.0.2 on 2026-04-12 18:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='combo',
            name='modal_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='modal_image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
