# Generated by Django 6.0.2 on 2026-04-19 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_combo_image_alter_combo_modal_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='image',
            field=models.ImageField(upload_to='combos/'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', null=True, upload_to='combos/modal/'),
        ),
        migrations.AlterField(
            model_name='homehero',
            name='image',
            field=models.ImageField(upload_to='hero/'),
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='image',
            field=models.ImageField(upload_to='partners/'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='image',
            field=models.ImageField(upload_to='process/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='modal_image',
            field=models.ImageField(blank=True, help_text='Image shown in quick-view modal (leave blank to use main image)', null=True, upload_to='products/modal/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
