# Generated by Django 6.0.2 on 2026-04-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_backfill_customer_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Stock Keeping Unit code for Shiprocket', max_length=100),
        ),
        migrations.AddField(
            model_name='combo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Weight in KG', max_digits=6),
        ),
        migrations.AddField(
            model_name='order',
            name='awb_code',
            field=models.CharField(blank=True, help_text='Airway Bill number for tracking', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('Prepaid', 'Prepaid')], default='COD', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='Stock Keeping Unit code for Shiprocket', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Weight in KG', max_digits=6),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Shipped', 'Shipped'), ('In Transit', 'In Transit'), ('Out for Delivery', 'Out for Delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('RTO', 'Returned to Origin'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
