# Generated by Django 6.0.2 on 2026-04-21 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_combo_sku_combo_weight_order_awb_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalPincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(db_index=True, max_length=10, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text="Optional label, e.g. 'Sector 12, Noida'", max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Local Pincode',
                'verbose_name_plural': 'Local Pincodes',
                'ordering': ['pincode'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_zone',
            field=models.CharField(choices=[('local', 'Local'), ('shiprocket', 'Shiprocket')], default='shiprocket', help_text="'Local' orders are handled in-house and not pushed to Shiprocket.", max_length=20),
        ),
    ]
