# Generated by Django 6.0.2 on 2026-04-22 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_localpincode_order_delivery_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shiprocket_order_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
