# Generated by Django 6.0.2 on 2026-04-22 17:18

import uuid
from django.db import migrations, models


def backfill_order_refs(apps, schema_editor):
    """Assign a unique DF-XXXXXXXX ref to every existing order."""
    Order = apps.get_model('core', 'Order')
    for order in Order.objects.filter(order_ref__isnull=True):
        for _ in range(10):
            candidate = f"DF-{uuid.uuid4().hex[:8].upper()}"
            if not Order.objects.filter(order_ref=candidate).exists():
                order.order_ref = candidate
                order.save(update_fields=['order_ref'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_add_index_shiprocket_order_id'),
    ]

    operations = [
        # Step 1: add the column as nullable (no unique yet — avoids default clash)
        migrations.AddField(
            model_name='order',
            name='order_ref',
            field=models.CharField(
                max_length=15, editable=False,
                null=True, blank=True,
                help_text='Auto-generated unique order reference, e.g. DF-A3F2B1C9',
            ),
        ),
        # Step 2: backfill existing rows with unique refs
        migrations.RunPython(backfill_order_refs, migrations.RunPython.noop),
        # Step 3: make it required + unique + indexed
        migrations.AlterField(
            model_name='order',
            name='order_ref',
            field=models.CharField(
                max_length=15, editable=False,
                null=False, blank=False,
                unique=True, db_index=True,
                help_text='Auto-generated unique order reference, e.g. DF-A3F2B1C9',
            ),
        ),
    ]
