# Generated by Django 6.0.2 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_add_razorpay_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shiprocket_sync_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_sync_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('not_required', 'Not Required')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shiprocket_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]