# Generated by Django 6.0.2 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_order_shiprocket_sync_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, to='core.combo'),
        ),
    ]