# Generated by Django 6.0.2 on 2026-05-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_orderitem_combo'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='breadth',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package breadth in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='combo',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package height in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='combo',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package length in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='breadth',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package breadth in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package height in cm', max_digits=6),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(decimal_places=2, default=10, help_text='Package length in cm', max_digits=6),
        ),
    ]
